apps:
- name: five-thousand
  ports:
  - 5001
  - 5200
  - 5300
  - 5400
  targets:
  - tcp-echo.fly.dev:5001
  - tcp-echo.fly.dev:5002
- name: six-thousand
  ports:
  - 6001
  - 6200
  - 6300
  - 6400
  targets:
  - tcp-echo.fly.dev:6001
  - tcp-echo.fly.dev:6002
  - bad.target.for.testing:6003
- name: seven-thousand
  ports:
  - 7001
  - 7200
  - 7300
  - 7400
  targets:
  - tcp-echo.fly.dev:7001
  - tcp-echo.fly.dev:7002
- name: broken
  ports:
  - 8001
  targets:
  - bad.target.for.testing:6003
  - bad.target.for.testing:6003
  - bad.target.for.testing:6003
  - bad.target.for.testing:6003
